// Generated by the gRPC protobuf plugin.
// If you make any local change, they will be lost.
// source: CloudApi.proto
#ifndef GRPC_CloudApi_2eproto__INCLUDED
#define GRPC_CloudApi_2eproto__INCLUDED

#include "CloudApi.pb.h"

#include <grpc++/impl/codegen/async_stream.h>
#include <grpc++/impl/codegen/async_unary_call.h>
#include <grpc++/impl/codegen/proto_utils.h>
#include <grpc++/impl/codegen/rpc_method.h>
#include <grpc++/impl/codegen/service_type.h>
#include <grpc++/impl/codegen/status.h>
#include <grpc++/impl/codegen/stub_options.h>
#include <grpc++/impl/codegen/sync_stream.h>

namespace grpc {
class CompletionQueue;
class Channel;
class RpcService;
class ServerCompletionQueue;
class ServerContext;
} // namespace grpc

namespace devmand {
namespace channels {
namespace cli {
namespace cloudapi {

class DataReceiver GRPC_FINAL {
 public:
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status sendData(
        ::grpc::ClientContext* context,
        const ::devmand::channels::cli::cloudapi::DataRequest& request,
        ::google::protobuf::Empty* response) = 0;
    std::unique_ptr<
        ::grpc::ClientAsyncResponseReaderInterface<::google::protobuf::Empty>>
    AsyncsendData(
        ::grpc::ClientContext* context,
        const ::devmand::channels::cli::cloudapi::DataRequest& request,
        ::grpc::CompletionQueue* cq) {
      return std::unique_ptr<::grpc::ClientAsyncResponseReaderInterface<
          ::google::protobuf::Empty>>(AsyncsendDataRaw(context, request, cq));
    }

   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface<
        ::google::protobuf::Empty>*
    AsyncsendDataRaw(
        ::grpc::ClientContext* context,
        const ::devmand::channels::cli::cloudapi::DataRequest& request,
        ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub GRPC_FINAL : public StubInterface {
   public:
    Stub(const std::shared_ptr<::grpc::ChannelInterface>& channel);
    ::grpc::Status sendData(
        ::grpc::ClientContext* context,
        const ::devmand::channels::cli::cloudapi::DataRequest& request,
        ::google::protobuf::Empty* response) GRPC_OVERRIDE;
    std::unique_ptr<
        ::grpc::ClientAsyncResponseReader<::google::protobuf::Empty>>
    AsyncsendData(
        ::grpc::ClientContext* context,
        const ::devmand::channels::cli::cloudapi::DataRequest& request,
        ::grpc::CompletionQueue* cq) {
      return std::unique_ptr<
          ::grpc::ClientAsyncResponseReader<::google::protobuf::Empty>>(
          AsyncsendDataRaw(context, request, cq));
    }

   private:
    std::shared_ptr<::grpc::ChannelInterface> channel_;
    ::grpc::ClientAsyncResponseReader<::google::protobuf::Empty>*
    AsyncsendDataRaw(
        ::grpc::ClientContext* context,
        const ::devmand::channels::cli::cloudapi::DataRequest& request,
        ::grpc::CompletionQueue* cq) GRPC_OVERRIDE;
    const ::grpc::RpcMethod rpcmethod_sendData_;
  };
  static std::unique_ptr<Stub> NewStub(
      const std::shared_ptr<::grpc::ChannelInterface>& channel,
      const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status sendData(
        ::grpc::ServerContext* context,
        const ::devmand::channels::cli::cloudapi::DataRequest* request,
        ::google::protobuf::Empty* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_sendData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* service) {}

   public:
    WithAsyncMethod_sendData() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_sendData() GRPC_OVERRIDE {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status sendData(
        ::grpc::ServerContext* context,
        const ::devmand::channels::cli::cloudapi::DataRequest* request,
        ::google::protobuf::Empty* response) GRPC_FINAL GRPC_OVERRIDE {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestsendData(
        ::grpc::ServerContext* context,
        ::devmand::channels::cli::cloudapi::DataRequest* request,
        ::grpc::ServerAsyncResponseWriter<::google::protobuf::Empty>* response,
        ::grpc::CompletionQueue* new_call_cq,
        ::grpc::ServerCompletionQueue* notification_cq,
        void* tag) {
      ::grpc::Service::RequestAsyncUnary(
          0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_sendData<Service> AsyncService;
  template <class BaseClass>
  class WithGenericMethod_sendData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* service) {}

   public:
    WithGenericMethod_sendData() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_sendData() GRPC_OVERRIDE {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status sendData(
        ::grpc::ServerContext* context,
        const ::devmand::channels::cli::cloudapi::DataRequest* request,
        ::google::protobuf::Empty* response) GRPC_FINAL GRPC_OVERRIDE {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
};

} // namespace cloudapi
} // namespace cli
} // namespace channels
} // namespace devmand

#endif // GRPC_CloudApi_2eproto__INCLUDED
